swagger: "2.0"
info:
  title: Decolar Service
  description: Decolar HTTP service
  version: ""
host: localhost:3333
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /aeroporto:
    post:
      tags:
      - decolar
      summary: create_aeroporto decolar
      operationId: decolar#create_aeroporto
      parameters:
      - name: create_aeroporto_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/DecolarCreateAeroportoRequestBody'
          required:
          - nome
          - pais_id
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/DecolarCreateAeroportoResponseBody'
            required:
            - id
            - nome
            - pais_id
            - created_at
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/DecolarCreateAeroportoInvalidFieldsResponseBody'
      schemes:
      - http
  /compania:
    post:
      tags:
      - decolar
      summary: create_compania decolar
      operationId: decolar#create_compania
      parameters:
      - name: create_compania_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/DecolarCreateCompaniaRequestBody'
          required:
          - nome
          - pais_id
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/DecolarCreateCompaniaResponseBody'
            required:
            - id
            - nome
            - pais_id
            - created_at
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/DecolarCreateCompaniaInvalidFieldsResponseBody'
      schemes:
      - http
  /pais:
    post:
      tags:
      - decolar
      summary: create_pais decolar
      operationId: decolar#create_pais
      parameters:
      - name: create_pais_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/DecolarCreatePaisRequestBody'
          required:
          - nome
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/DecolarCreatePaisResponseBody'
            required:
            - id
            - nome
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/DecolarCreatePaisInvalidFieldsResponseBody'
      schemes:
      - http
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  DecolarCreateAeroportoInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_aeroporto_invalid_fields_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  DecolarCreateAeroportoRequestBody:
    title: DecolarCreateAeroportoRequestBody
    type: object
    properties:
      nome:
        type: string
        example: 7lv
        minLength: 1
      pais_id:
        type: string
        example: 74C53540-E974-ABFF-2565-6BF99F9017B2
        format: uuid
    example:
      nome: ozy
      pais_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
    required:
    - nome
    - pais_id
  DecolarCreateAeroportoResponseBody:
    title: DecolarCreateAeroportoResponseBody
    type: object
    properties:
      created_at:
        type: string
        example: Dolores numquam voluptates voluptate aspernatur qui voluptatibus.
      id:
        type: string
        example: Qui iusto et facilis.
      nome:
        type: string
        example: Exercitationem quo quis modi.
      pais_id:
        type: string
        example: Deleniti asperiores pariatur.
    example:
      created_at: Voluptatibus nisi tempore.
      id: Animi quod harum maxime ipsa est.
      nome: Dolorem maiores commodi dolorem.
      pais_id: Sunt in nesciunt.
    required:
    - id
    - nome
    - pais_id
    - created_at
  DecolarCreateCompaniaInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: create_compania_invalid_fields_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  DecolarCreateCompaniaRequestBody:
    title: DecolarCreateCompaniaRequestBody
    type: object
    properties:
      nome:
        type: string
        example: g0j
        minLength: 1
      pais_id:
        type: string
        example: FF1D889F-0741-6290-783B-66E606310D86
        format: uuid
    example:
      nome: vc
      pais_id: 77EB7E77-465C-FCC6-CEC6-11F6C8938D24
    required:
    - nome
    - pais_id
  DecolarCreateCompaniaResponseBody:
    title: DecolarCreateCompaniaResponseBody
    type: object
    properties:
      created_at:
        type: string
        example: Deleniti ut ducimus esse.
      id:
        type: string
        example: Maiores omnis numquam at a.
      nome:
        type: string
        example: Veritatis quaerat maiores optio.
      pais_id:
        type: string
        example: Dolores sit amet culpa quisquam doloremque in.
    example:
      created_at: Veritatis eum.
      id: Nobis enim et quibusdam similique.
      nome: Doloremque ratione excepturi.
      pais_id: Corrupti ut ut ut adipisci similique.
    required:
    - id
    - nome
    - pais_id
    - created_at
  DecolarCreatePaisInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_pais_invalid_fields_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  DecolarCreatePaisRequestBody:
    title: DecolarCreatePaisRequestBody
    type: object
    properties:
      nome:
        type: string
        example: Et natus quia.
    example:
      nome: Excepturi ullam voluptas laborum ratione est.
    required:
    - nome
  DecolarCreatePaisResponseBody:
    title: DecolarCreatePaisResponseBody
    type: object
    properties:
      id:
        type: string
        example: Temporibus voluptas ut possimus.
      nome:
        type: string
        example: Est sint est et at quia modi.
    example:
      id: Adipisci cupiditate eaque.
      nome: Distinctio dolor molestias dolor velit aut non.
    required:
    - id
    - nome
